### ISSUE TITLE
Support for the nullsoft, inno, wix, and additional installer types

### ISSUE THREAD

**Issue by superusercode** [ptorr-msft/WinGetYamlGenerator#22]
Per https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv0.1.md

**Comment by ptorr-msft** [comment]
Are those specific file-types, or are they just ways of creating EXE / MSI / MSIX?

**Comment by superusercode** [comment]
@ptorr-msft they're used in place of the exe installer type when you want to skip setting silent flags for popular installer solutions (see https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv0.1.md)

**Comment by ptorr-msft** [comment]
Done, thanks for suggestion.
