### ISSUE TITLE
Add support for switches

### ISSUE THREAD

**Issue by perplexityjeff** [ptorr-msft/WinGetYamlGenerator#26]
Add support for switches. For example an EXE that requires the /S silent argument switch cannot be used. As far as I am aware?

**Comment by ptorr-msft** [comment]
Good suggestion. Haven't had a chance to do any work on this lately...

**Comment by perplexityjeff** [comment]
I see packages get added by people on the winget package repo but because the silent switches aren't added if people aren't technical enough but want to help overlook this easily. Would be great to add it but I respect your time :)
