### ISSUE TITLE
Remove HTTPS check for installers

### ISSUE THREAD

**Issue by JanPokorny** [ptorr-msft/WinGetYamlGenerator#29]
An error is shown when attempting to enter a HTTP installer URL:

![obrazek](https://user-images.githubusercontent.com/4580066/96176067-204fa400-0f2c-11eb-8593-8933f2503a76.png)

`winget` does not actually have this limitation, however.

![obrazek](https://user-images.githubusercontent.com/4580066/96176300-745a8880-0f2c-11eb-8a89-216d66f97bf2.png)

There are apps published on HTTP-only websites (why? don't ask me), and since the installer authenticity is verified by embedded hash anyway, it is not necessary to check this.

**Comment by ptorr-msft** [comment]
Thanks for the report @JanPokorny . I will double-check with the package-manager folks to see if this is changing (or has changed recently).

**Comment by JanPokorny** [comment]
@ptorr-msft Interestingly, it seems like there's some code in the master branch appearing to require HTTPS (https://github.com/microsoft/winget-cli/commit/dd840a8559fe5456ec537082d5552a81b333aa9b#diff-8b85fbdd761cdf57bd78f3c741f457c9ef458ab251dce447c578bcb9833ee9af), but neither the most recent release of `winget` nor the Azure pipelines for manifest repository (https://github.com/microsoft/winget-pkgs/pull/4209) seem to care.

**Comment by Vukky123** [comment]
![image showing winget refusing to add a source that is on http](https://i.imgur.com/CeVYIAi.png)

That code appears to be for adding sources, not for package downloads.
